### ISSUE TITLE
add testing and CI

### ISSUE THREAD

**Issue by aqreed** [Xero64/pyvlm#1]
Hello, I wonder if you have thought about adding unit testing and continuous integration

I am also writing a [VLM code](https://github.com/aqreed/PyVLM) and I find you project interesting indeed

**Comment by Xero64** [comment]
Hi, thank you for your interest in my project, and my apologies for the late reply.

I have just started this project and learning software development in the process.

I plan to do unit tests eventually, probably by version 0.2.0, but write now I am trying to get the code to a functional baseline by version 0.1.0.

That doesn't mean I haven't done any validation and testing. In recent commits, I have created test cases that tie up with theory.

I will keep this as an issue and target it for a future milestone.
