### ISSUE TITLE
Exclamations in feedback messages

### ISSUE THREAD

**Issue by Interster** [Xero64/pyvlm#3]
Running Aircraft.json the following warning message is generated.
It has an exclamation.  Warning messages with exclamations is shouting and in my view to be avoided.  Same as all caps messages which are like shouting.  Please consider removing exclamations.

```F:\WinPython3_81\notebooks>pyvlm Aircraft.json
Convergence failed for 60deg Banked Turn Cruise!

**Comment by Xero64** [comment]
Updated as requested.
